<h1 class="header"><?php echo $title ?></h1>
<table class="striped sortable" style="width: 100%;" id="authorizations_list">
<thead>
<tr>
    <th class="nosort"><?php echo _("Action") ?></th>
    <th><?php echo _("Module") ?></th>
    <th><?php echo _("ID") ?></th>
    <th><?php echo _("Reference") ?></th>
    <th><?php echo _("Amount") ?></th>
    <th><?php echo _("User") ?></th>
    <th><?php echo _("Created") ?></th>
    <th><?php echo _("Updated") ?></th>
    <th><?php echo _("Status") ?></th>
    <th><?php echo _("Method") ?></th>
</tr>
</thead>
